apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: gop-file-server
  name: gop-file-server
spec:
  volumes:
    - name: data-store
      persistentVolumeClaim:
        claimName: data-pvc    
  containers:
  - image: kodekloud/fileserver
    name: gop-file-server
    resources: {}
    volumeMounts:
      - mountPath: /web
        name: data-store

  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}