- name: Generate the CSR Creation
  hosts: localhost
  gather_facts: no
  vars:
     ansible_python_interpreter: "{{ ansible_playbook_python }}"


  tasks:
    - debug:
       msg: '{{ tower_job_inventory_name }}'
    #- name: Calling SSL CSR creation Role
     # ansible.builtin.include_role:
     #        name: ssl_role
      
    
