apiVersion: v1
kind: Service
metadata:
  name: vote-service
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 80
      nodePort: 31000
  selector:
      name: vote-deployment-pod
      app: demo-vote-application
     