apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jekyll-site
  namespace: development
spec:
  storageClassName: local-storage
  volumeName: jekyll-site
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi