---
- name: checking the variable value
  ansible.builtin.assert:
    that:
      - csr_create_unique_name|default('', true) != ''
      - csr_create_cn| default('', true) != '' 
    fail_msg: "Unique_name and Create_common name is the mandatory variable"
    success_msg: " Varibale 'csr_create_unique_name' and 'csr_create_cn' passed value validation!"


- name: Generate Private Key
  community.crypto.openssl_privatekey:
    path: "{{ csr_create_stage_dir }}/{{ csr_create_unique_name }}.key"
    size: 2048
  tags:
    - csr_create_generate

- name: Generate Certificate Signing Request
  community.crypto.openssl_csr:
    path: "{{ csr_create_stage_dir }}/{{ csr_create_unique_name }}.csr"
    privatekey_path: "{{ csr_create_stage_dir }}/{{ csr_create_unique_name }}.key"
    common_name: "{{ csr_create_cn }}"
    #state: present
    country_name: 'SG'
    locality_name: 'Singapore'
    state_or_province_name: 'SG'
    organization_name: 'RHB Bank'
    organizational_unit_name: 'IT'
    subject_alt_name: 'DNS:{{ csr_create_alt_names  | default(csr_create_cn)}}'
  register: _csr_create_gen
  tags:
    - csr_create_generate


- name: Display generate CSR output
  ansible.builtin.debug: var=_csr_create_gen
  when: csr_create_debug|bool
  tags:
    - csr_create_generate


- name: Save CSR filename
  ansible.builtin.set_fact:
    csr_create_filename: "{{ csr_create_stage_dir }}/{{ csr_create_unique_name }}.csr"
  tags:
    - csr_create_filenamae

- ansible.builtin.debug:
    var: csr_create_filename
  when: csr_create_debug|bool

- name: Read the CSR content from the file
  ansible.builtin.set_fact:
    csr_create_csr: "{{ lookup('file', csr_create_filename) }}"
  tags:
    - csr_create_csr

- ansible.builtin.debug: 
    var: csr_create_csr
  #when: csr_create_debug|bool

- name: Set stats and expose CSR
  ansible.builtin.set_stats:
    data:
      csr: "{{ csr_create_csr }}"
  tags:
    - csr_create_set_stats

- name: Remove private key
  ansible.builtin.file:
    path: "{{ csr_create_stage_dir }}/{{ csr_create_unique_name }}.key"
    state: absent
  tags:
    - csr_create_cleanup

- name: Remove the CSR file
  ansible.builtin.file:
    path: "{{ csr_create_stage_dir }}/{{ csr_create_unique_name }}.csr"
    state: absent
  tags:
    - csr_create_cleanup
