---
##need community.crypto collection before use it
# - name: Generate Certificate Signing Request config file
#   template:
#     src: csr_config.j2 
#     dest: "{{ csr_create_stage_dir }}/{{ csr_create_unique_name }}.txt"
#     mode: 0644
#     backup: yes
#   tags:
#     - csr_create_config_file

# - name: Generate Certificate Signing Request
#   command: "openssl req -new -sha256 -nodes -out {{ csr_create_stage_dir }}/{{ csr_create_unique_name }}.csr -newkey rsa:2048 -keyout {{ csr_create_stage_dir }}/{{ csr_create_unique_name }}.key -config {{ csr_create_stage_dir }}/{{ csr_create_unique_name }}.txt"
#   register: _csr_create_gen
#   tags:
#     - csr_create_generate

- name: Generate Private Key
  openssl_privatekey:
    path: "{{ csr_create_stage_dir }}/{{ csr_create_unique_name }}.key"
    size: 2048
  tags:
    - csr_create_generate

- name: Generate Certificate Signing Request
  openssl_csr:
    path: "{{ csr_create_stage_dir }}/{{ csr_create_unique_name }}.csr"
    privatekey_path: "{{ csr_create_stage_dir }}/{{ csr_create_unique_name }}.key"
    common_name: "{{ csr_create_cn }}"
    #state: present
    country_name: 'In'
    locality_name: 'Tamil'
    state_or_province_name: 'Tamil'
    organization_name: 'bank'
    organizational_unit_name: 'SBI IT'
    subject_alt_name: 'DNS:{{ csr_create_alt_names }}'
  register: _csr_create_gen
  tags:
    - csr_create_generate

- name: Display generate CSR output
  debug: var=_csr_create_gen
  tags:
    - csr_create_generate


# - name: Display generate CSR output
#   debug: var=_csr_create_gen.stderr_lines
#   tags:
#     - csr_create_generate

# - name: Remove the config file
#   file:
#     path: "{{ csr_create_stage_dir }}/{{ csr_create_unique_name }}.txt"
#     state: absent
#   tags:
#     - csr_create_cleanup

- name: Save CSR filename
  set_fact:
    csr_create_filename: "{{ csr_create_stage_dir }}/{{ csr_create_unique_name }}.csr"
  tags:
    - csr_create_filenamae

- debug:
    var: csr_create_filename
  when: csr_create_debug|bool

- name: Save CSR content
  set_fact:
    csr_create_csr: "{{ lookup('file', csr_create_filename) }}"
  tags:
    - csr_create_csr

- debug: 
    var: csr_create_csr
  when: csr_create_debug|bool

- name: Set stats and expose CSR
  set_stats:
    data:
      csr: "{{ csr_create_csr }}"
  tags:
    - csr_create_set_stats

- name: Remove private key
  file:
    path: "{{ csr_create_stage_dir }}/{{ csr_create_unique_name }}.key"
    state: absent
  tags:
    - csr_create_cleanup

- name: Remove the CSR file
  file:
    path: "{{ csr_create_stage_dir }}/{{ csr_create_unique_name }}.csr"
    state: absent
  tags:
    - csr_create_cleanup
