   - name: Grant the developer permission to given user in survey end
     uri:
      url: "{{ jira_API_url }}/project/{{ jira_project_name }}/role/10001/"
      method: POST
      user: '{{ jira_user }}'
      password: '{{ cyberark_jira_password }}'
      force_basic_auth: yes
      body: '{ "user": {{jira_unique_id_list}} }'
      body_format: json
      headers:
        Accept: application/json
        content-type: application/json
      validate_certs: no
      use_proxy: no
      status_code: 200,201,404
      return_content: yes
     register: jira_user_access
     retries: '3'
     delay: '3'
     when: jira_unique_id_list|length > 0
